### ISSUE TITLE
Will there be a download script?

### ISSUE THREAD

**Issue by agirbau** [Event-AHU/EventVOT_Benchmark#1]
Thank you for this work, looks incredible!

I would like to know if you plan to add a script or similar to download the dataset from terminal, as accessing from the browser might not always be possible. Thanks so much!

**Comment by wangxiao5791509** [comment]
@agirbau  Hi, thanks for your attention to our work. It seems that the dropbox download link can be adjusted for download via wget on the terminal. You can try the following script: 

wget https://www.dropbox.com/scl/fo/fv2e3i0ytrjt14ylz81dx/h?rlkey=6c2wk2z7phmbiwqpfhhe29i5p"&"dl=1

Please let me know  whether it works for the download. Thanks.

**Comment by agirbau** [comment]
Thanks for the quick response!

It seems to work, I'm downloading the dataset and get back to you once it's finished. Thanks so much!

**Comment by agirbau** [comment]
It's working perfectly thanks so much!

P.S. Maybe you could add it to the README so other people can use it. Also, it would be nice to use the -O parameter to give a name to the downloaded file.

**Comment by wangxiao5791509** [comment]
@agirbau  Thanks for your feedback. We will update this in the README.
