### ISSUE TITLE
很想知道这个代码要跑多久。

### ISSUE THREAD

**Issue by zhangnengbo** [Event-AHU/EventVOT_Benchmark#12]
老师，我已经下载好了eventvot数据集 并且泡在一块4090的显卡上面。问题是一直在训练epoch 0.不知道老师花了多久时间训练。

**Comment by zhangxiaodi** [comment]
这个代码数据预处理用try catach 捕捉异常的 没有报错。 所以最好先生成voxel和list.txt和train.txt.     至于跑多久 看你用的是什么卡4090上面跑挺快的。

**Comment by wsasdsda** [comment]
> 老师，我已经下载好了eventvot数据集 并且泡在一块4090的显卡上面。问题是一直在训练epoch 0.不知道老师花了多久时间训练。

单卡3090上，我跑的时候一个epoch 30分钟左右.

**Comment by 12138flash** [comment]
> 这个代码数据预处理用try catach 捕捉异常的 没有报错。 所以最好先生成voxel和list.txt和train.txt. 至于跑多久 看你用的是什么卡4090上面跑挺快的。

能请教一下生成Voxel这步是怎么做的吗？运行时一直显示训练集中缺少.mat文件
