### ISSUE TITLE
两个数据集版本的区别

### ISSUE THREAD

**Issue by Ambrumax** [Event-AHU/EventVOT_Benchmark#15]
作者您好，我注意到您提供了两个数据集，分别是事件图像版本和完整版，前者好像缺少.csv文件，如果我现在想复现您的代码，是否只能使用完整版数据集，或者您是否可以提供事件图像版本数据集缺少的文件。

**Comment by wangxiao5791509** [comment]
@Ambrumax  原始 event stream 的数据格式是 *.raw 文件，但是这种文件不要读取，因此我们将其转为了 *.csv 文件方便读取。所有的 event 数据都来自该文件，且数据集是全面的，因此，不是缺少文件。event frame （即图像版本）或者 event voxel 都是根据 *.raw 文件堆叠得到的。
