### ISSUE TITLE
运行python tracking/create_default_local_file.py --workspace_dir . --data_dir ./data --save_dir ./output后未生成文件夹

### ISSUE THREAD

**Issue by Ambrumax** [Event-AHU/EventVOT_Benchmark#16]
运行python tracking/create_default_local_file.py --workspace_dir . --data_dir ./data --save_dir ./output后，lib/train/admin/和lib/test/evaluation下的local.py中的路径均已更新，但我发现HDETrack文件夹下并没有生成workspace、data、和output文件夹，包括后文提到的CEUTrack_ep0050.pth和mae_pretrain_vit_base要放的pretrain_models文件夹和HDETrack_S_ep0050.pth要放的output/checkpoints/train/hdetrack/hdetrack_eventvot文件夹都需要自己手动生成吗

**Comment by wsasdsda** [comment]
您好！感谢您的关注。数据集的路径以及项目路径可以在lib/train/admin/local.py和lib/test/evaluation/local下手动添加。pretrained_models需要手动上传到指定文件夹。关于HDETrack_S_ep0050.pth，如果是从头训练则不需要放，如果是直接拿来测试，则需要您放到指定的路径下面。

**Comment by wsasdsda** [comment]
> 运行python tracking/create_default_local_file.py --workspace_dir . --data_dir ./data --save_dir ./output后，lib/train/admin/和lib/test/evaluation下的local.py中的路径均已更新，但我发现HDETrack文件夹下并没有生成workspace、data、和output文件夹，包括后文提到的CEUTrack_ep0050.pth和mae_pretrain_vit_base要放的pretrain_models文件夹和HDETrack_S_ep0050.pth要放的output/checkpoints/train/hdetrack/hdetrack_eventvot文件夹都需要自己手动生成吗

您好！感谢您的关注。数据集的路径以及项目路径可以在lib/train/admin/local.py和lib/test/evaluation/local下手动添加。pretrained_models需要手动上传到指定文件夹。关于HDETrack_S_ep0050.pth，如果是从头训练则不需要放，如果是直接拿来测试，则需要您放到指定的路径下面。
