### ISSUE TITLE
数据集文件损坏问题

### ISSUE THREAD

**Issue by HusterYoung** [Event-AHU/EventVOT_Benchmark#2]
您好，我在下载Event-VOT数据集并解压的时候发现报错，提示该文件损坏，请问有解决方案吗？（我下载了两次解压都是同样位置报错，应该排除了下载过程中出现问题的可能）
![))U3 {IJ)JJQI3RFG C N`7](https://github.com/Event-AHU/EventVOT_Benchmark/assets/35907047/f9106aea-4814-4d67-b19c-be945b4c4de0)

**Comment by HusterYoung** [comment]
该文件位于Raw Event Data下的Train Split中

**Comment by wangxiao5791509** [comment]
@HusterYoung  就这一个文件是破损的，还是说某一个压缩包是坏的？

**Comment by HusterYoung** [comment]
> @HusterYoung 就这一个文件是破损的，还是说某一个压缩包是坏的？

很怪，我换了个解压工具就不报错了……现在没事了现在
