### ISSUE TITLE
请问lib_clip这个包是什么，还有运行test.py的时候test/list.txt文件是否有提供

### ISSUE THREAD

**Issue by LI474525323** [Event-AHU/EventVOT_Benchmark#3]
![image](https://github.com/Event-AHU/EventVOT_Benchmark/assets/55075770/543bb8d2-dc74-4537-a481-17c293493fa6)

![image](https://github.com/Event-AHU/EventVOT_Benchmark/assets/55075770/3f63fbba-bd94-4f94-8f7c-fcc57893fd1e)

**Comment by HusterYoung** [comment]
lib_clip应该就是lib吧，作者可能忘了改文件夹名字了

**Comment by wsasdsda** [comment]
您好，感谢提醒。lib_clip就是lib，test/list.txt文件是测试集的视频名称列表 @LI474525323
