### ISSUE TITLE
请问能否增加对单个aedat4文件的tracking功能？

### ISSUE THREAD

**Issue by Hocason** [Event-AHU/EventVOT_Benchmark#6]

**Comment by wangxiao5791509** [comment]
我们这个工作的核心目标就是实现针对 event 单个模态的跟踪；如果是涉及到双模态融合的思路，请参考 
https://github.com/Event-AHU/COESOT
https://github.com/wangxiao5791509/VisEvent_SOT_Benchmark 

另外，aedat4 的文件读取等也可以从上述两个 github 中找到。感谢关注！

**Comment by Hocason** [comment]
感谢您的回答，是我问题表述的不清，我也是希望使用对event单个模态的跟踪功能，
我想要通过您的工作对我的event行人数据生成bbox，
但是数据集本体太大了，我很难下载，所以现在我没搞清应该把我的数据做成什么样子load进网络。

**Comment by wangxiao5791509** [comment]
@Hocason   这个需要看你想要把 event 弄成什么形式的表示，再用网络进行处理。

**Comment by Hocason** [comment]
> @Hocason 这个需要看你想要把 event 弄成什么形式的表示，再用网络进行处理。

我是直接把一段event以（t，x，y，p）全存在txt文件里了，但是我看您的dataloader好像更复杂
