### ISSUE TITLE
EventVOT压帧时间戳

### ISSUE THREAD

**Issue by BarrelTitor** [Event-AHU/EventVOT_Benchmark#7]
你好，请问EventVOT有提供压帧时间戳吗，我在提供的数据集中只找到了csv文件的时间数据，关于GT和事件的对齐时间戳似乎没有提供

**Comment by wangxiao5791509** [comment]
@BarrelTitor  我们当时标注的时候是将单个 event stream 堆叠为固定的视频帧，因此，可以根据这个信息来得到其 gt 时间戳。
